server:
  servlet:
    context-path: /spring-th
  error:
    include-binding-errors: never
    include-message: never
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@ics-t-development.cztekutconfc.ap-northeast-2.rds.amazonaws.com:1521:ORCL
    username: root
    password: icstroot
    hikari:
      auto-commit: false