server:
  port: 8080
  servlet:
    context-path: /spring-th

  error:
    include-message: never
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@10.100.70.7:1521:XE
    username: student##
    password: student##
    hikari:
      auto-commit: false

  jackson:
    property-naming-strategy: SNAKE_CASE